### ISSUE TITLE
Will not load more if still in view

### ISSUE THREAD

**Issue by bruce** [hhff/ember-infinity#10]
This is a bit of an edge case, but in the event you set `perPage` low enough so that it would take more than two requests to fill the viewport, it simply stops after the second page of results is loaded.

My expectation is that it would continue to load items until the `infinity-loader` was pushed out of view or the results were all retrieved/displayed.

**Comment by hhff** [comment]
You're saying that after the first call to `infinityLoad`, if the loader is still in view, it won't retrigger a new load automatically, right?

Should be simple enough to solve - my main concern is keeping it inline with "actions up, data down"

**Comment by bruce** [comment]
Correct. My naïve guess was that it may have had to do with a debounce or a run once, but I didn't have a chance to investigate further. Thanks!

**Comment by hhff** [comment]
I'll look into this shortly, I reckon observing the length of `infinityModel` and checking if it's still in view (and loading more if so) directly after the length changes should do the trick

**Comment by hhff** [comment]
(from the infinity-loader, that is)

**Comment by kellyselden** [comment]
fixed in #44
