### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offset' of undefined

### ISSUE THREAD

**Issue by bryanhickerson** [hhff/ember-infinity#100]
When I turn on destroyOnInfinity I get an exception in _checkIfInView after all the data has loaded and presumably the loader has been deleted. Everything is working fine since the data has already been loaded, but it seemed like there is something worth looking in to.

Exception:
```
Uncaught TypeError: Cannot read property 'offset' of undefined_checkIfInView @ infinity-loader.js:45
```

Line in question:
```
var selfOffset = this.$().offset().top;
```

Template:
```
{{resources-list resources=model}}
{{#infinity-loader infinityModel=model destroyOnInfinity=true}}
  <i class="fa fa-circle-o-notch fa-spin fa-2x" />
{{/infinity-loader}}
```

**Comment by davidgoli** [comment]
Thanks for filing the bug, I've seen this too, and the fix seems trivial. In my case I've removed the `destroyOnInfinity` property and handle hiding the infinity loader using CSS (the `.reached-infinity` class gets added to the `.infinity-loader` when infinity is reached.

:+1: for a fix

**Comment by bryanhickerson** [comment]
Thanks for the workaround

**Comment by hhff** [comment]
thanks @bryanhickerson !  should be a simple fix!  :+1: for this work around for now

**Comment by venkz** [comment]
Hey I was not using the destroyOnInfinity flag but I still run into this issue when I  run Ember test suite on pages that have infinity scroll. It is not reproducible consistently but I  see this quite often. 

Could you give me any clue as to why this occurs and what is happening here... 

I updated to 0.2.1 V hoping it will fix the issue but no luck!

@bryanhickerson @davidgoli @hhff

**Comment by KennedyTedesco** [comment]
@venkz The same issue here. Even not using `destroyOnInfinity` the problem ocurs.

**Comment by ilucin** [comment]
I have the same issue. It happens when component is destroying.
PR #138 is addressing this but I don't think it's doing the right think. It should check for `this.isDestroying` flag instead of `this.isDestroyed`.

**Comment by KennedyTedesco** [comment]
@ilucin :+1:

**Comment by ilucin** [comment]
Quick hack (until this gets resolved) is to reopen InfinityLoaderComponent and override _shouldLoadMore(). I did it in my project like [this](https://gist.github.com/ilucin/149553d7745f5ca6cbcc).

I've also created a PR #145 to fix this correctly.
