### ISSUE TITLE
Not Working With JSON API

### ISSUE THREAD

**Issue by IsaiahJTurner** [hhff/ember-infinity#109]
I am sending this response <img width="870" alt="screen shot 2015-12-04 at 2 26 25 pm" src="https://cloud.githubusercontent.com/assets/3732588/11599146/27a95d30-9a93-11e5-9c6f-d04b873ec221.png">

but get the error" Error: Ember Infinity: Could not fetch Infinity Model. Please check your serverside configuration." which is pretty much useless for diagnosing the issue so I still don't know what's wrong.

**Comment by IsaiahJTurner** [comment]
I tried changing "data" to "items" and still got the error.

**Comment by kellyselden** [comment]
discussion started here #97

**Comment by hhff** [comment]
closing so discussion can continue at #97
