### ISSUE TITLE
Normalize parameters passed to infinityModel

### ISSUE THREAD

**Issue by bruce** [hhff/ember-infinity#11]
Just a thought for a post #9 world.

The current API for `infinityModel` involves passing `perPage` and `startingPage` properties -- which are then converted to `per_page` and `page` parameters for the backend.

Once people start having the ability to pass arbitrary parameters to `infinityModel`, I can imagine (especially if they're simultaneously working on the backend API) they may _accidentally_ provide `page` (vs `startingPage`) and `per_page` (vs `perPage`) options -- which would [currently] be ignored.

I think it might make sense that the logic is a bit more forgiving, eg:

```javascript
var startingPage = options.startingPage || options.page || 1;
var perPage      = options.perPage || options.per_page || this.get('_perPage');
```

**Comment by hhff** [comment]
:+1: - I feel `startingPage` has a different purpose to `page`, as it is specific to the infinite scroll itself, but I do agree re: `perPage`.  

Would love a PR on this!
