### ISSUE TITLE
ember-cli-htmlbars is out of date

### ISSUE THREAD

**Issue by stefanpenner** [hhff/ember-infinity#114]
(Includes, old broccoli filter that is slow, and hurts build performance)

https://github.com/hhff/ember-infinity/blob/master/package.json#L46

**Comment by kellyselden** [comment]
Doing god's work @stefanpenner, thanks a lot!

**Comment by hhff** [comment]
thanks stef!

**Comment by stefanpenner** [comment]
:+1:
