### ISSUE TITLE
Uncaught Error: <...> had no action handler for: infinityLoad

### ISSUE THREAD

**Issue by teckays** [hhff/ember-infinity#117]
This error is thrown when the `infinity-loader` component enters the view.

```
DEBUG: -------------------------------
DEBUG: Ember             : 2.2.0
DEBUG: Ember Data        : 2.2.1
DEBUG: jQuery            : 2.1.4
DEBUG: -------------------------------
```

**Comment by davidgoli** [comment]
@teckays have you mixed in the InfinityRoute mixin to one of the parent action handlers? This is the default action that Ember Infinity sends, you'll need to handle it somewhere in your code if you want to use it.

**Comment by teckays** [comment]
@davidgoli I have mixed it in my index route.

```
import Ember from 'ember';
import InfinityRoute from "ember-infinity/mixins/route";

export default Ember.Route.extend(InfinityRoute, {

});
```

**Comment by teckays** [comment]
OK, the problem might be that I've put `{{infinity-loader infinityModel=items}}` inside a custom component and did not bubble this action up with `this.sendAction()`. No I have moved it inside my `templates/index.hbs`, the error is gone, however the results are not fetched when hitting the end of the page. I only have the initial 20 results and that's it. It only prints `Infinite Model Entirely Loaded.` on the page.

**Comment by hhff** [comment]
@teckays - please be sure to follow the readme carefully - your latest issue is in your server's response (in the `meta` payload)

**Comment by NvnTiwari** [comment]
Hi, Getting Uncaught error "had no action handler for *" {{ action "doSearch" "ab"}}.
