### ISSUE TITLE
Where does `loadMoreAction` action get's handled?

### ISSUE THREAD

**Issue by teckays** [hhff/ember-infinity#118]
in `_checkIfInView()` you call `this.sendAction('loadMoreAction');` but I don't see this action to be handled anywhere. do I have to handle it myself?

**Comment by hhff** [comment]
it bubbles out of the component and is handled in the `InfinityRoute`

**Comment by teckays** [comment]
@hhff well I don't find this action inside `mixins/route.js`, perhaps there is a special way of handling it. As a side note, I don't seem to be successful implementing this library in my app. I know the issue is closed but I will post some of my code, perhaps you have a clue why it's not working for me.

**/app/routes/index.js**
``` lang-js
import Ember from 'ember';
import InfinityRoute from "ember-infinity/mixins/route";

export default Ember.Route.extend(InfinityRoute, {

  perPageParam: "filter[limit]",
  pageParam: "filter[skip]",
  totalPagesParam: "meta.total",

  model() {

    var lastMonth = new Date();
    lastMonth.setDate(lastMonth.getDate() - 31);

    return Ember.RSVP.hash({
      videos: this.infinityModel("video", {
        perPage: 20,
        startingPage: 1,
        filter: {
          where: {created: {gte: lastMonth.toISOString()}},
          order: 'sourceViews DESC',
          include: ['channel']
        }
      })
    })
  }

});
```

**/app/templates/index.hbs**
``` lang-html
<div class="index-page">
  {{#if model.videos}}
    {{video-cards-grid items=model.videos}}
  {{/if}}
  {{infinity-loader infinityModel=model.videos}}
</div>
```

**endpoint response object**
```
{
    "meta": {
       "total": 1000
    },
    "data": [
        {...},
        {...}
    ]
}
```

then on the page it prints `Infinite Model Entirely Loaded.` I have debugged from the lib directly and for some reason the total pages gets passed as `undefined`.

Ideas?

**Comment by hhff** [comment]
The corresponding route action is named `infinityLoad` - you can see the external action named explicitly [here](https://github.com/hhff/ember-infinity/blob/master/addon/components/infinity-loader.js#L9).

Because your infinity model lives at `model.videos`, you'll want to add this:

```
  model() {
    var lastMonth = new Date();
    lastMonth.setDate(lastMonth.getDate() - 31);

    return Ember.RSVP.hash({
      videos: this.infinityModel("video", {
        perPage: 20,
        startingPage: 1,
        modelPath: 'controller.model.videos', // <--- This line
        filter: {
          where: {created: {gte: lastMonth.toISOString()}},
          order: 'sourceViews DESC',
          include: ['channel']
        }
      })
    })
  }
```

Give that a try and let me know :+1:

**Comment by teckays** [comment]
@hhff hmm, same thing, the initial 20 items are successfully loaded, however when I hit the bottom it still says `Infinite Model Entirely Loaded.` and no requests are made when inspecting the developer console as well the ember console data shows 20 results.

**Comment by hhff** [comment]
I'd need to see the repo directly to know what's going on sorry @teckays !  I'm sure it's a super simple config thingy

**Comment by teckays** [comment]
@hhff unfortunately I can't give you full access to the repository, however I can make some gists.

**Comment by teckays** [comment]
@hhff https://gist.github.com/teckays/ab6a86368f6b1e2f32a4
