### ISSUE TITLE
Infinity model allow skip-like pagination

### ISSUE THREAD

**Issue by teckays** [hhff/ember-infinity#122]
I don't know if it currently supports, could not find anything about it in the documentation, but would be great if it would support skip-like pagination. What I mean is that some of the api backends do not accept pationation like `1, 2, 3, etc.` it works with skip. Example: (asuming you have 20 items per page) then `20, 40, 60, etc.`.

**Comment by teckays** [comment]
For now I solved this using this hack:

```
_buildParams: function(nextPage){
    nextPage = (nextPage - 1) * perPage;
    return this._super(nextPage);
  }
```

A more elegant, built-in solution is needed!

**Comment by hhff** [comment]
We've got support for this - you can do this in a *nicer way* using `boundParams` and the `afterInfinityModel` hook - or by overriding the `extractMeta` hook in your serializer to convert your limit into "pages"

**Comment by teckays** [comment]
@hhff thank you, I will give this a try, however I have expected a config-like way of defining this. Anyway, will work for now.

**Comment by kellyselden** [comment]
@teckays We are always open to doing things better/different if the right idea/PR comes along :smile:

**Comment by hhff** [comment]
:100:
