### ISSUE TITLE
load data from nested url

### ISSUE THREAD

**Issue by ffaerber** [hhff/ember-infinity#124]
is it possible to load data from a JSONAPI relationship
categories/2/products?page=1&per_page=10

Many thanks

**Comment by davidgoli** [comment]
Yep, there's nothing stopping you. If you're having problems, I'd suggest looking at `ember-data-url-templates` to customize your adapter. This isn't really a concern of `ember-infinity`.

**Comment by ffaerber** [comment]
ember-data-url-templates was helpfull.
I also found a good article on that topic.
http://blog.ksol.fr/ember-data-working-with-nested-api-resources/

thanks
