### ISSUE TITLE
Loader with custom scrollable never fires

### ISSUE THREAD

**Issue by nandorstanko** [hhff/ember-infinity#126]
@mariuszzak 
I had to change the following lines in https://github.com/hhff/ember-infinity/blob/master/addon/components/infinity-loader.js to make this work how I expected:

```
_selfOffset() {
    if (this.get('_customScrollableIsDefined')) {
      return this.$().position().top + this.get("_scrollable").scrollTop();
    } else {
      return this.$().offset().top;
    }
  },
```

Maybe I'm missing something, but adding this.get("_scrollable").scrollTop() to the top position is unnecessary. Returning only this.$().position().top, in case when there is a custom scrollable item defined, is enough. In the current code _selfOffset is always bigger than _bottomOfScrollableOffset, if the   loader is not in the view.

**Comment by davidgoli** [comment]
@hhff This is a regression that broke with `0.2.1`

**Comment by hhff** [comment]
yup.  @mariuszzak can you take a look here?

**Comment by mdentremont** [comment]
One thing that did change (which affected us) was `_checkIfInView` was renamed to `_loadMoreIfNeeded` (https://github.com/hhff/ember-infinity/compare/v0.2.0...v0.2.1)

**Comment by jimmay5469** [comment]
I believe I have found the issue... `this.$().position().top` in the snippet above is making an assumption that the `_scrollable` element is the direct parent of the loader which may or may not be the case. What I believe we need is `this.$().offset().top - this.get("_scrollable").offset().top` which does not make any assumptions. I will try to create a PR shortly and make sure all the tests continue to pass with the change.

**Comment by hhff** [comment]
thats @jimmay5469 !

yup correct - it's been on my todo list to fix for sometime now... I would really love a PR for it!

**Comment by jimmay5469** [comment]
PR submitted! Hopefully it helps!
