### ISSUE TITLE
Can we load it in reverse?

### ISSUE THREAD

**Issue by v3ss0n** [hhff/ember-infinity#132]
For chat rooms , we need to load data in reverse order , is there feature for it?

**Comment by hhff** [comment]
yessir

```
afterInfinityModel(newObjects) {
  return newObjects.reverse()
}
```

**Comment by hhff** [comment]
but this is better done on the server of course

**Comment by v3ss0n** [comment]
Yes it will be on server
But the display order is reversed. latest first and scroll up to load more
Thanks gonna test it out

**Comment by williamweckl** [comment]
@v3ss0n did you do that? How can I configure Infinity to scroll up instead down?

**Comment by williamweckl** [comment]
I'm trying to make infinity model unshift new objects instead push, is that possible?

**Comment by williamweckl** [comment]
**update** to unshift I did:

```javascript
InfinityRoute.reopen({
  _doUpdate(newObjects) {
    let infinityModel = this._infinityModel();
    return infinityModel.unshiftObjects(newObjects.get('content'));
  }
});
```

But I did not figured out how to invert the scroll event to UP instead DOWN yet.

**Comment by davidgoli** [comment]
@williamweckl the "trigger" for loading more is in the `infinity-loader` component, and is implemented like so:

```js
  _bottomOfScrollableOffset() {
    return this.get('_scrollable').height() + this.get("_scrollable").scrollTop();
  },

  _triggerOffset() {
    return this._selfOffset() - this.get('triggerOffset');
  },

  _shouldLoadMore() {
    if (this.get('developmentMode') || this.isDestroying || this.isDestroyed) {
      return false;
    }

    return this._bottomOfScrollableOffset() > this._triggerOffset();
  },
```

If you want to trigger load in a direction that's not down, you'd have to reimplement this code (especially `_bottomOfScrollableOffset` and `_shouldLoadMore`). You might try subclassing `infinity-loader`, or reimplementing with your own component. Better yet, a pull request to indicate direction either in an attribute or as a different component would be helpful...

**Comment by williamweckl** [comment]
Opened :)
https://github.com/hhff/ember-infinity/pull/182
