### ISSUE TITLE
Preferred method of handling server error

### ISSUE THREAD

**Issue by JakeDluhy** [hhff/ember-infinity#133]
We are using Ember Infinity for our infinite scrolling feed (loving it btw). One case we want to handle, however, is when there is a server error, and it returns a 404 JSON (or 500). We would like to gracefully fail, and show a message. I added a catch
```
return this.infinityModel('activity', params)
.catch(() => {

});
```
Which kind of works... I still get the error `Uncaught Error: Property set failed: object in path "controller.model" could not be found or was destroyed.` And the `Loading Infinite Model...` text is still displayed. I could ignore the error and have a class get rid of the text in this case, but I was wondering if there's a best way to handle this case. Thanks!

**Comment by JakeDluhy** [comment]
I did a bit more researching, and discovered that Ember has some error handling options from the route's model hook. https://guides.emberjs.com/v2.3.0/routing/loading-and-error-substates/

I just defined an error template and went from there.

**Comment by hhff** [comment]
nice!
