### ISSUE TITLE
TypeError: infinityModel.pushObjects is not a function

### ISSUE THREAD

**Issue by progand** [hhff/ember-infinity#144]
I use Ember 2.4.1 with ember-data 2.4.0
I have a problem when I use RSVP hash as a route model:
```
return Ember.RSVP.hash({
      feed: this.store.findRecord('rssfeed', params.feed_id),
      items: this.infinityModel('rssitem', {
        perPage: 5,
        startingPage: 1,
        filter: {
          feed: params.feed_id
        }
      })
    });
```
Initial loading works fine but I have an error on update:
```
ember.debug.js:32123 TypeError: infinityModel.pushObjects is not a function
    at _doUpdate (route.js:308)
    at _nextPageLoaded (route.js:329)
    at route.js:246
    at tryCatch (ember.debug.js:53542)
    at invokeCallback (ember.debug.js:53557)
    at publish (ember.debug.js:53525)
    at ember.debug.js:32081
    at Queue.invoke (ember.debug.js:333)
    at Object.Queue.flush (ember.debug.js:397)
    at Object.DeferredActionQueues.flush (ember.debug.js:205)
```

I can see that `infinityModel.pushObjects` is undefined in `route.js:308`:
```
    _doUpdate: function _doUpdate(newObjects) {
      var infinityModel = this._infinityModel();
      return infinityModel.pushObjects(newObjects.get('content'));
    },
```

How can I solve the problem?

**Comment by sylwiaeb** [comment]
@progand Look here https://github.com/hhff/ember-infinity/issues/67 Basically, you need to add `modelPath` for items and then setupController.

**Comment by progand** [comment]
Thanks!
It's good idea to add an example to docs.

**Comment by sylwiaeb** [comment]
There is one..  :)

**Comment by progand** [comment]
Ah yes. You're right.
I think it would be nice to have simple example with `RSVP.hash` and `modelPath` but its not necessary.

**Comment by JasonLin37** [comment]
Hey guys, I know this is a closed issue, but I'm still get this error even though I have added modelPath for items and also setupController.

**Comment by hhff** [comment]
try this @JasonLin37 

```
setupController(controller, model) {
  controller.set('listings', model.listings);
},
```

**Comment by JasonLin37** [comment]
@hhff Thank you so much, that worked great.
