### ISSUE TITLE
Preserve scrolling position and model data when navigating from/to InfinityRoute

### ISSUE THREAD

**Issue by mphasize** [hhff/ember-infinity#146]
Thanks for this great addon! Super easy to setup and customize. :+1: Here's one more feature request. :)

---

After scrolling through a long infinity list and choosing an item which takes us to a new route, it would be great if we could navigate back to the exact same point in the infinity list.

This behavior would need to preserve data on the route and tell InfinityRoute not to re-fetch data, when transitioning back to the route. It would also need to save and restore window.scroll position when re-entering the InfinityRoute.

It could also be done without preserving data, and instead remembering and restoring the current page, but then the InfinityRoute would have to be scrollable forwards *and* backwards. Probably harder to do.

Has anybody solved this already?
Are there others who would benefit from such a feature?
Is it within scope of ember-infinity?

**Comment by hhff** [comment]
Hi @mphasize !  Thanks for the kind words!

We've had a few feature requests for the preservation of data on a route.  I don't currently know a good pattern for this - controllers are singletons, and persisting the data there is trivial, but the `infinityModel` method always assumes that you're starting  from 0.

Perhaps a `shouldFlushInfinityModel` hook (or similar) could be the solution here!  If you'd like to take a stab at that, we'd very much appreciate it.

The mechanism for preserving the scroll position is not something that Ember Infinity should be concerned with - but when we have a system for preserving data and only flushing it when necessary, this part will be trivial.  Take a look at this: https://dockyard.com/blog/2014/05/05/preserve-scroll-position-in-ember-apps

**Comment by mphasize** [comment]
Hehe, I have been using that exact same Preserve-Scroll-Mixin before, but it's based on Views, which are deprecated and would have to be refactored. I think the scroll-position and the data in an infinite scroll are actually closely coupled: If the data is flushed, the scroll position has to be reset, otherwise preserved. But you're right, it may not be a concern for `ember-infinity`, but could be a potential extension, like `ember-infinity-preserved`. 

At the moment I don't have the time to try an implementation, but I will need this feature for the app we're building, so maybe in some weeks. :)

**Comment by davidgoli** [comment]
I'd also recommend looking at this addon: https://github.com/runspired/smoke-and-mirrors It's a work in progress but much more fully-featured for scrolling (though it doesn't offer anything like the route mixin of ember-infinity). You'd still have to preserve the already-fetched items though. For that, what I've done in the past is assign the `infinityModel` to the controller (or to a service) instead of to the route, and then clear it when it's appropriate for your app. That way, the collection stays in memory between visits to the route.

**Comment by JasonLin37** [comment]
Hey guys, I know this thread has been closed, but just wanted to find our if you guys are still planning on adding such a feature.

I was doing some research on this and found the article on dorkyard as you linked earlier and also found a [stack-overflow post](http://stackoverflow.com/questions/30081661/ember-js-restore-scroll-on-history-reset-scroll-on-link) which seems to be interesting. 

I tried it on my app, and if i had scrolled past page 1 on my infinite route it will take me to the bottom of the page 1 when going back to the infinite route and then it will stop there.

I'm new to ember so not exactly sure why that's the case but thought it was interesting and wanted to bring it to your attention.

**Comment by hhff** [comment]
thanks @JasonLin37 !  I'd take a look at the comment above yours - david's suggestion is how I'd handle something like this.  Ember Infinity just aims to be a low level tool that doesn't know too much about your dom.

**Comment by Redsandro** [comment]
Has anyone successfully made a workaround for this?

I notice that the all the model instances are still loaded when navigating back to the page with ember-infinity. But they are not used. The first `perPage` _n_ are reloaded and the rest is ignored.

**Comment by snewcomer** [comment]
Yes this is likely due to the lazy loading behaviour.  The browser encounters that code and says "I'm lazy loading".  Some external data structure would be needed to reinstate the full list.
