### ISSUE TITLE
will this work with ember 2.4?

### ISSUE THREAD

**Issue by v3ss0n** [hhff/ember-infinity#152]
I am using lastest ember , will this work with latest ember-cli too ?

**Comment by hhff** [comment]
Yessir, we run our tests against canary / beta & the current release, so I don't see why not!

**Comment by v3ss0n** [comment]
Thanks a lot , i come from qooxdoo and I  am looking around dynamic and auto-adjusting , infinite lists implementations.
I also found ember's own list-view https://github.com/emberjs/ember-collection what are the key differences?
