### ISSUE TITLE
Adding without scroll action, Deleting records

### ISSUE THREAD

**Issue by Diodeus** [hhff/ember-infinity#154]
1) If I add records on the object on modelPath, how can I trigger them to be rendered without having to push them individually? I'd like it to be able to just listen for changes and refresh the contents.

2) How do I get it to update when I remove a record?

**Comment by hhff** [comment]
Hi @Diodeus !

1) This is unrelated to ember-infinity - just use `pushObjects` and the list should update automatically

2) using `removeAt` or `removeObject/s` should do the trick

Essentially - just use the `MutableArray` methods on the infinityModel (usually at `controller.model`), and the template will update.
http://emberjs.com/api/classes/Ember.MutableArray.html

**Comment by hhff** [comment]
closing - let me know if you need further help
