### ISSUE TITLE
How to load a hasMany relationship?

### ISSUE THREAD

**Issue by andrewhavens** [hhff/ember-infinity#159]
I have a route that loads a primary model and displays one of its `hasMany` relationships. I want to use `ember-infinity` to paginate the `hasMany` relationship. Currently, my template simply calls `{{#each model.children as |child|}}`. What do I need to modify in order to make this work with `ember-infinity`?

**Comment by hhff** [comment]
Hi @andrewhavens !

Currently we can't do that out of the box - Ember Infinity has a hard dependency on there being an paginated endpoint for the model you're actually displaying.

There's various ways to get around this, but the path of least resistance is to add/modify an API endpoint for your child model, like so:

```
host.com/api/child_models?parent_model_id=231&per_page=5&page=1
```

That way you can use a param (or bound param, if it's dynamic) for `parent_model_id` and paginate that relationship.

Please reopen if this doesn't solve your issue!

**Comment by andrewhavens** [comment]
I think part of my question was simply how to change from a single model route to a route that returns multiple. I ended up with something like this. Posting it here in case it helps anyone else in the future.

```
# in coffeescript:

  model: (params) ->
    Ember.RSVP.hash
      parent: @store.findRecord('parent', params.parent_id)
      children: @infinityModel 'child', parent_id: params.parent_id, modelPath: 'controller.model.children', perPage: 20, startingPage: 1
```

**Comment by hhff** [comment]
perfect!

**Comment by yogeshjain999** [comment]
Above solution is not working for me. API request is still going to:
`host.com/api/children?per_page=5&page=1&parent_id=1`
