### ISSUE TITLE
Introduction to ember-infinity on The Ember Show at Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [hhff/ember-infinity#162]
Would you someone familiar with this library be interested in giving a lightning talk about this addon on The Ember Show? We're recording the next episode on June 11th followed by July 2nd. 

An introduction to <addon> talk is about 15 minutes long and covers the following:
- Why was this addon created?
- When should it be used?
- How does one get started?
- What should the person be aware of?

You can see some of the previously recorded introduction talks on [Global Ember Meetup Videos](https://www.embermeetup.com/videos?category=addon-introductions) page.

Would you be able to give this talk?

**Comment by hhff** [comment]
Hi @taras !  Totally man!  June 11th is a bit tight for me but July 2nd I could do.  Lemme know ❤️

**Comment by taras** [comment]
July 2nd it is :)

**Comment by hhff** [comment]
<3

**Comment by taras** [comment]
@hhff We're going to move July 2nd event to July 9th because of holidays. Does July 9th work for you?

**Comment by hhff** [comment]
@taras sure thing!
