### ISSUE TITLE
ember-infinity demo as Ember Twiddle for presenting issues

### ISSUE THREAD

**Issue by openhouse** [hhff/ember-infinity#165]
`ember-infinity` forever!

Here is the `ember-infinity` demo as an Ember Twiddle.  People could fork this to mock up their issues.  This could be something for the docs? https://ember-twiddle.com/c08988c41ef999bc0ef34bb0d92c17e5

Ember Twiddle is a great JS Bin sort of thing which *lets you use addons* in an `ember-cli` style layout.

I made this on my way to mocking up an issue I'm having (HeroicEric/ember-group-by#12).  I want to group items from an `infinityModel`.  But it seems that using `ember-group-by` causes the DOM for whole list to redraw whenever `ember-infinity` adds new items to the model.  This slows with each page.  Any tips on how to group `infinityModel` items would be appreciated!

j a m i e

**Comment by hhff** [comment]
yo @openhouse !  this is a little tricky.  In a situation like this, I'd try keeping the infinityModel array privately, and then creating the groups based on the data in the infinityModel, via the `afterInfinityModel` hook.

Check it out:
https://github.com/hhff/ember-infinity#afterinfinitymodel

Not sure this approach would work out of the box with `ember-group-by`, but looking at the logic there, it shouldnt be all that hard to replicate & modify for a data source that's getting larger & larger over time.

Please re-open if this doesn't quite solve your problem!

**Comment by openhouse** [comment]
@hhff  I will try this, thanks!
