### ISSUE TITLE
Can it work without totalPages?

### ISSUE THREAD

**Issue by techsoldaten** [hhff/ember-infinity#166]
I am trying to load content through an API that lacks a total_pages parameter in the response. No way to change it, all we get is a list of articles.

Is it possible to get ember-infinity working without this parameter? Right now, it loads the first 10 articles and displays a message 'Infinite Model Entirely Loaded'. What I would like to do is simply have the list stop scrolling when no results are returned from the server.

**Comment by hhff** [comment]
Yup!

```
export default Route.extend(InfinityRoute, {
  _canLoadMore: true
})
```
