### ISSUE TITLE
Dynamic change scrollable element

### ISSUE THREAD

**Issue by jobsboris27** [hhff/ember-infinity#172]
Hi! Do you support dynamic changing scrollbar element?
I mean, if i detect mobile device, i will change element where user can scroll.
 `  {{infinity-loader infinityModel=model scrollable=(if mobile ".mobileList" ".desktopList"))}}`

**Comment by hhff** [comment]
Not currently @jobsboris27 but it would be trivial to implement with the `didRecieveAttrs` lifecycle hook on the infinity-loader component!

**Comment by jobsboris27** [comment]
That component are in node_modules. @hhff, how can I use didRecieveAttrs?
Sorry, stupid question)

**Comment by jobsboris27** [comment]
I did that `export default infinityLoader.extend({`

**Comment by hhff** [comment]
nice!
