### ISSUE TITLE
Breaks Ember-Inspector

### ISSUE THREAD

**Issue by charlwillia6** [hhff/ember-infinity#177]
I am using a third party ember addon called ember-osf.  I have checked all the code in their mixin and it is all correct with what is on the ember-infinity README.md file.  I am getting the following error:

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Could not find module `ember-infinity/mixins/route` imported from `ember-osf/mixins/infinity-custom`
Stack trace: Error: Could not find module `ember-infinity/mixins/route` imported from `ember-osf/mixins/infinity-custom`
```

This is only on the route tab of the ember inspector.  I am using Google Chrome.  Ember inspector will not load the Routes information because of this error.  Is this an error with Ember Inspector?

**Comment by snewcomer** [comment]
@charlwillia6 Just seeing this.  If you still have a problem, open this issue back up and ping us here and I'll look into it (I didn't see it in ember-osf anymore).  Otherwise going to close for now.
