### ISSUE TITLE
Fastboot Error

### ISSUE THREAD

**Issue by sgasser** [hhff/ember-infinity#186]
With `ember fastboot` I get following error:

```
There was an error running your app in fastboot. More info about the error: 
 TypeError: Cannot read property 'height' of undefined
    at _bottomOfScrollableOffset
```

"ember-cli": "2.8.0"
"ember-cli-fastboot": "1.0.0-beta.9"
"ember-infinity": "0.2.6"

**Comment by willviles** [comment]
+1

It's because `_loadMoreIfNeeded` is called on afterRender and that calls `_shouldLoadMore`, which references DOM height.

Could do with conditional checking presence of FastBoot:

```javascript
_loadMoreIfNeeded() {
  if (this._shouldLoadMore() && typeof FastBoot === 'undefined') {
    this.sendAction('loadMoreAction', this.get('infinityModel'));
  }
}

```

**Comment by Redsandro** [comment]
This mean #186 can be closed? Or still needs release?

**Comment by willviles** [comment]
Can be closed! [Definitely](https://github.com/hhff/ember-infinity/blob/0.2.8/addon/components/infinity-loader.js#L62) in 0.2.8.

**Comment by Redsandro** [comment]
I thought so! Fastboot seems to work. I have no close power tho.  :angel:

**Comment by hhff** [comment]
good catch!
