### ISSUE TITLE
Just a suggestion about total pages. 

### ISSUE THREAD

**Issue by weragoda88** [hhff/ember-infinity#188]
Hi I love ember infinity, you guys are awesome, just an suggestion about updating the total pages  in _nextPageLoaded. so don't have to re calculate the result count in the server, because  default _totalPages is 0
  _nextPageLoaded(newObjects) {
    const totalPages = newObjects.get(this.get('totalPagesParam'));

   if (totalPages >0) {
      this.set('_totalPages', totalPages);
    }
......
}
thank you.

**Comment by snewcomer** [comment]
@weragoda88 hey thanks for the issue!  If you are still using ember-infinity, we are moving towards a 1-0 release.  See the branch [here](https://github.com/hhff/ember-infinity/tree/1-0).

Pertaining to your issue, you can see an example [here](https://github.com/hhff/ember-infinity/blob/1-0/addon/lib/infinity-model.js#L114) of the page incrementing.  Let me know if this helps at all.  Feel free to continue the discussion.  Closing for now :+1:
