### ISSUE TITLE
infinityModel with explicit id

### ISSUE THREAD

**Issue by danilovaz** [hhff/ember-infinity#191]
I have a `route/show` that show's a selected chat, how can I do this is `.infinityModel` passing the explicit `id` of chat selected?
```js
return Ember.RSVP.hash({
      // --> What I need
      //chat: this.store.findRecord('chat', params.chat_id)

      // --> What I try
      chat: this.infinityModel("chat", params.chat_id, { perPage: 20, startingPage: 0, modelPath: 'controller.model.chat' })
    })
```

Another question about this: how can I paginate my `hasMany` relationship in this scenario?

`chat` hasMany `chatMessages`, there is an easy way to paginate `chatMessages`? I'm using JSONAPI, so when I get `chat` I'm receive `chatMessages` too.

Thank's so much! :tada:

**Comment by snewcomer** [comment]
@danilovaz behind the scenes, infinityModel uses query so will fetch a list of results.  Paginating a hasMany relationship is possible with something like this https://github.com/mdehoog/ember-data-has-many-query but you need to configure your backend to do so.  Closing for now, but ping me if you have any other questions.
