### ISSUE TITLE
undeclared variable loadedAny 

### ISSUE THREAD

**Issue by khavq** [hhff/ember-infinity#205]
Hi there,

I got an issue with "afterInfinityModel" method. Can anybody help me out?

Thank you,

this is my route:

import Ember from 'ember';
import InfinityRoute from "ember-infinity/mixins/route";

export default Ember.Route.extend(InfinityRoute, {
	_minId: undefined,
  	_minUpdatedAt: undefined,
  	_canLoadMore: true,

	model() {
		//return this.store.findAll('rental');
		//return this.infinityModel("rental", { perPage: 5, startingPage: 1 });
		return this.infinityModel("rental", {}, {
			min_id: '_minId',
			min_updated_at: '_minUpdatedAt'
		});
	},

	afterInfinityModel(rentals) {
		loadedAny = rentals.get('length') > 0;
	    this.set('_canLoadMore', loadedAny);

        this.set('_minId', rentals.get('lastObject.id'));
		this.set('_minUpdatedAt', rentals.get('lastObject.updated_at').toISOString());
	} 
	
});

And I got this message

Error while processing route: rentals assignment to undeclared variable loadedAny afterInfinityModel@http://localhost:4200/assets/ember-frontend.js:407:16
_afterInfinityModel/<@http://localhost:4200/assets/vendor.js:94380:24
tryCatch@http://localhost:4200/assets/vendor.js:68726:12

**Comment by nojacko** [comment]
You're gonna need to put a `var` or `let` before `loadedAny = rentals.get('length') > 0;`

**Comment by hhff** [comment]
what @nojacko said - this isn't an ember infinity issue :)
