### ISSUE TITLE
Chrome performance when using mouse wheel

### ISSUE THREAD

**Issue by kevinansfield** [hhff/ember-infinity#206]
I've been fighting a [performance issue in Chrome](https://github.com/TryGhost/Ghost/issues/7934) that only seems to appear when using the mouse wheel to scroll. I've instrumented the `_loadNextPage` method like so

```javascript
_loadNextPage() {
    this.set('_loadingMore', true);

    console.time('_loadNextPage');
    return this._requestNextPage()
      .then((newObjects) => {
        this._nextPageLoaded(newObjects);

        return newObjects;
      })
      .finally(() => {
        console.timeEnd('_loadNextPage');
        this.set('_loadingMore', false);
      });
  },
```

and this is the result - note how delayed the network requests are in Chrome when using the mouse wheel, sometimes > 4sec!

<img width="585" alt="screen shot 2017-02-02 at 17 34 13" src="https://cloud.githubusercontent.com/assets/415/22561372/daf7d0ca-e96f-11e6-9984-637ec09e6e6f.png">

I've attempted to use a higher `eventDebounce` value but was unable to notice any improvements.

The buggy behaviour has so far appeared in Chrome 55, 56, and Canary 58. I've not been able to reproduce in Safari or Firefox. Most of the testing has been on macOS but I saw the same behaviour running Chrome 56 in a Windows 10 VM.

I've got a [timeline profile screenshot](https://github.com/TryGhost/Ghost/issues/7934#issuecomment-276975908) that shows the long period of inactivity despite a very quick server response when the request is finally triggered.

If anyone has any ideas for how to debug this further or what the problem might be I'd be extremely grateful! Thanks.

**Comment by hhff** [comment]
Interesting @kevinansfield !  I haven't hit this yet.  I'll keep an ear to the ground!

**Comment by kevinansfield** [comment]
After some more investigation I think I'm running into this behaviour http://stackoverflow.com/questions/35024301/xhr-settimeout-promise-not-finishing-until-scrolling-stops-in-chrome

I am consistently able to increase the loading time by scrolling while the network request is being triggered. If I disable Chrome's "threaded scrolling" so that scroll events happen on the main thread the effect is even more pronounced, to the point where I can almost prevent the next page from loading indefinitely.

I backed up my conclusion by modifying `_shouldLoadMore` to always return `true` so that on refresh  every page is loaded sequentially. Without scrolling every page is loaded in ~60ms, as soon as I start using the scroll wheel whilst the pages are loading the loading time jumps, if I continuously scroll up and down a little the next page never loads although interestingly my `_loadNextPage` timer only reports a delay of a few seconds once I stop scrolling.

**Comment by kevinansfield** [comment]
I eventually tracked this down to a Chrome "optimisation" behaviour that is enabled when you have touch event handlers registered. Disabling touch events in Ember's EventDispatcher solved the problems I was seeing:

```
let App = Application.extend({
    Resolver,
    modulePrefix: config.modulePrefix,
    podModulePrefix: config.podModulePrefix,

    customEvents: {
        touchstart: null,
        touchmove: null,
        touchend: null,
        touchcancel: null
    }
});
```

Another confounding factor which may/may not have been an issue I noticed when profiling - Chrome seemed to be flagging long frames (~30ms) when scrolling, as far as I can tell that time was taken up entirely by Chrome's `scrollUpdate` and `mouseWheel` events, there was only a ms or two that were JS related and it was the same when I'd removed `ember-infinity` to test. I bring this up as I've seen mention that the delayed setTimeout and xhr behaviour can be triggered when frames are taking >16ms.

**Comment by hhff** [comment]
Thanks @kevinansfield - very annoying that this new jank something you're wrestling with!  Closing this for now as it doesn't seem related to Ember Infinity - but if you'd like to continue to track you findings here I'm sure the community would find it super useful!
