### ISSUE TITLE
Specify custom store

### ISSUE THREAD

**Issue by Redsandro** [hhff/ember-infinity#209]
Is there a trick to specify a custom store?

E.g.:

```
secondStore: Ember.inject.service('some-other-store')
```

How do I use `secondStore` in stead of the default store?

**Comment by hhff** [comment]
Not currently - are you talking about a second Ember Data store?  Right now ember-infinity heavily relies on Ember Data.

I know it's possible to have different ember data stores - so if that's your scenario let's make it work!

**Comment by Redsandro** [comment]
Ok, I'll create a PR. :+1:
