### ISSUE TITLE
Use multiple times the same query-parameter-key

### ISSUE THREAD

**Issue by jevanlingen** [hhff/ember-infinity#211]
My backend uses Jersey (Java); to send a list you just provide the same key [multiple](http://stackoverflow.com/questions/13750010/jersey-client-how-to-add-a-list-as-query-parameter) times. For example, if you want to send a list with values 'A', 'B' and 'C' the query string would look like `?list=A&list=B&list=C`.

But how can I accomplish this with ember-infinity? Digging in the documentation, there seems no options to provide a list at all. 

N.B.
There isn't much about query parameters in the [JSON API Spec](http://jsonapi.org/format/#query-parameters) either.

**Comment by hhff** [comment]
Hi @jevanlingen !

I've never actually seen that style of query param before - I have seen something like `?ids=[1,2,3]` though.  I've seen `?ids[]=1&ids[]=2` also.

Anyway - no we don't support this unfortunately - but we accept PRs!  I'd love to include this if possible!

**Comment by jevanlingen** [comment]
Yeah I must say it would not be my format of choice. Thanks for the quick reply though!

If I am correct, the `?ids[]=1&ids[]=2` is not supported either? As far as I see it, only the `?ids=[1,2,3]` format can used at the moment, because no multiple keys are used.

Tomorrow I will try to write a PR to support different formats.

**Comment by hhff** [comment]
Yup, a stringified array is the only thing supported.

Thankyou!  Here's a good place to start:
https://github.com/hhff/ember-infinity/blob/master/addon/mixins/route.js#L286

**Comment by jevanlingen** [comment]
After reading and searching, I understood the fix should not be within the `ember-infinity` add-on. Ember infinity just [calls](https://github.com/hhff/ember-infinity/blob/master/addon/mixins/route.js#L274) the `query` method, so a serializer will do the job. After searching more, I found the [right](http://stackoverflow.com/a/43249332/2049986) answer!
