### ISSUE TITLE
Could not find module `ember-infinity/mixins/route`

### ISSUE THREAD

**Issue by kgcorner** [hhff/ember-infinity#213]
I am trying to Implement infinite-scrolling using ember-infinity. I have followed the documentation only but I am getting error "Could not find module ember-infinity/mixins/route" 
Below is my code:

`       
         import Ember from 'ember';
         import InfinityRoute from 'ember-infinity/mixins/route';

         export default Ember.Route.extend(InfinityRoute,{
         store: Ember.inject.service(),

    model(){
        var inflector = Ember.Inflector.inflector;
        
        inflector.irregular('feed', 'feeds.php');
        inflector.uncountable('advice');
        let user = JSON.parse(localStorage.getItem('user'));
        let token = localStorage.getItem('token');
        if(user != null){
            //return this.get('store').query('feed',{page:1,userid:user.id,token:token});
            return this.infinityModel("feed", { perPage: 12, startingPage: 1,userid:user.id,token:token });
        }
    } ,
    actions:{
      getDetails(feed){
        console.log("Getting details of "+feed.id);
      }
    }
     });
`

Version I am using 0.2.8
EMber-js version 2.0+

**Comment by hhff** [comment]
hi @kgcorner - the only reason this would happen is if ember-infinity is not properly installed.  (Perhaps someone npm installed it but didn't persist it to package.json)

try `ember install ember-infinity` from the root of your app.
