### ISSUE TITLE
had no action handler

### ISSUE THREAD

**Issue by NvnTiwari** [hhff/ember-infinity#221]
Hi, i am getting error on action "had no action handler for: doSearch""
<button class="btn btn-success" {{action "doSearch" "ab"}}></button>

**Comment by snewcomer** [comment]
@NvnTiwari Hi!  Well that stinks :) !  So ember-infinity has an API, which involves defining  something like this in your route: `this.infinityModel("product", { perPage: 12, startingPage: 1 });` and then defining a component like this in your template `{{infinity-loader infinityModel=model}}` (from the README).

My initial thought is that action is specific to your app, so needs to be defined on a component or route.  Would be happy to help, but would need a reproducible ember-twiddle https://ember-twiddle.com/.  In this case, I believe it does not relate to ember-infinity.

**Comment by snewcomer** [comment]
I'm going to close this issue.  Lmk if you can reveal any new info related to your problem and would be happy to help!
