### ISSUE TITLE
Use ember-infinity with button no longer works with ember 2.13.3

### ISSUE THREAD

**Issue by jeremyguarini** [hhff/ember-infinity#223]
After updating an existing app to ember 2.13.3 the load more button no longer works. I upgraded from ember 2.8. I don't see any errors on console. The experience I get is that clicking the button simply doesn't do anything. I also noticed that the button no longer updates to reflect that all records have been loaded (even when setting _canLoadMore to false).

Please let me know if you need anything else.

**Comment by hhff** [comment]
Can u Hi @jeremyguarini !

Are you sending the `infinity model` with the action from the load-more button?

```
  click: function(){    
    this.sendAction('action', this.get('infinityModel'));
  }
```

We made a recent change that it's now required, so that infinity models on nested routes work as expected 👍

**Comment by jeremyguarini** [comment]
I see that now there sendaction now has args set and that the load-more-button includes infinityModel. After adding changes it's working again. Thanks so much for then quick response and help!

**Comment by hhff** [comment]
glad its working!
