### ISSUE TITLE
Compatibility with ember-pouch 

### ISSUE THREAD

**Issue by macoun** [hhff/ember-infinity#225]
I'm not sure if ember-infinity is supposed to work with ember-pouch hand in hand. So, my apologies if this is not a proper question/request.

I'm using an ember-pouch adapter for ember data, which apparently doesn't work well with ember-infinity. This is what I get.

> "undefined is not an object (evaluating 'Object.keys(matcher)')"

Is ember-infinity supposed to work with JSONAPI only? Is it possible to use ember-infinity with ember-pouch?

**Comment by snewcomer** [comment]
@macoun thanks for the issue! So is `"undefined is not an object (evaluating 'Object.keys(matcher)')"
` ember-infinity code or your code?  

Regarding your question if ember-infinity is supposed to work with JSONAPI only.  Ember-Infinity works with Ember Data or any other [custom](https://github.com/hhff/ember-infinity#custom-store) store you design.  So if ember-pouch's API is the same as ED (`query` to GET records), then it should work.

**Comment by macoun** [comment]
Thank you for the info @snewcomer and sorry for my poor error description. It is actually produced by the function `checkFieldsLogicallySound`  in file pouchdb.find.js.

```
var hasLogicalOperator = Object.keys(matcher).some(function (matcherKey) {
    return !(isNonLogicalMatcher(matcherKey));
  });

```

It is probably a side effect rather than the actual problem. I recently switched to pouchdb since it has an offline database possibility which is great. 

I had only to replace my RESTAPIAdapter with the pouchdb adapter and it worked like a charm. So I guess it is using the same ED. In fact, pouchdb.find.js seems to be the part where the query is built. But I'm not very experienced with ember data in general and google couldn't find any useful information for the combination ember-infinity + ember-pouch. 

I guess I'll dive deeper and post again when I have more useful information.

**Comment by snewcomer** [comment]
Closing for now.  If you find anything more, lmk and would be happy to help.
