### ISSUE TITLE
Data not loaded

### ISSUE THREAD

**Issue by rizkysyazuli** [hhff/ember-infinity#226]
I'm using infinity with the button mode. But no data is loaded every time the button is clicked.

```javascript
// the page route
export default Ember.Route.extend(InfinityRoute, {
  ...

  perPageParam: 'limit',
  pageParam: 'page',
  totalPagesParam: 'meta.total_pages',

  model() {
    return RSVP.hash({
      ...

      articles: this.infinityModel('article', {
        perPage: 6,
        startingPage: 1,
        modelPath: 'model.articles'
      })
    })
  },

  ...
});
```

```html
<!-- the page template -->
<section class="section-articles">
  <div class="row small-up-1 medium-up-2">
    {{#each model.articles as |article|}}
      <div class="columns">
        {{article/article-post article=article}}
      </div>
    {{/each}}
  </div>

  <div class="row">
    <div class="columns small-12">

      <div class="article-load text-center">
        {{lego/button-load-more action="infinityLoad" infinityModel=model.articles buttonClass="button playgroup"}}
      </div>

    </div>
  </div>
</section>
```

The button component is pretty much the same as the example aside from some cosmetic markup changes.

Here's how my data looked like. But it's been normalized and the `data` node is named `article` just like the model name.

```json
{
    "data": [ ... ],
    "meta": {
        "total_pages": 39
    }
}
```

**Comment by snewcomer** [comment]
https://github.com/hhff/ember-infinity/issues/223

**Comment by rizkysyazuli** [comment]
@snewcomer the action inside the button component?

```js
// load-more-button
export default Ember.Component.extend({
  loadText: '...',
  loadedText: '...',

  click() {
    this.sendAction('action', this.get('infinityModel'));
  }
});
```

**Comment by rizkysyazuli** [comment]
oh, using the built-in `infinity-loader` component doesn't work as well.

```handlebars
{{infinity-loader infinityModel=model.articles}}
```

Not sure if it's related, but here's my normalizer:

```js
export default DS.RESTSerializer.extend({
  normalizeResponse(store, primaryModelClass, payload, id, requestType) {
    payload = {
      article: payload.data,
      meta: payload.meta
    };

    return this._super(store, primaryModelClass, payload, id, requestType);
  }
});
```

And the original server response:
```json
{
    "data": [ ... ],
    "meta": {
        "total_pages": 39
    }
}
```

**Comment by rizkysyazuli** [comment]
okay. problem solved. the problem is in the `modelPath`, which should be `controller.model.modelName`.

**Comment by MatthewPardini** [comment]
I know this issue is closed, but I've exhausted other resources. I can't get the infinityLoad to work with a button click. I am passing the correct model and it loads when I use {{#infinity-loader}} instead of a button. 

My controller looks like this:
`	actions: {
		loadMore(infinityModel) {
			this.infinity.infinityLoad(infinityModel);
		}
	}
`

Its template looks like this:
`{{load-more-button loadMore=(action "loadMore") infinityModel=races}}`

My load-more-button component looks like this:
`    click(){
        this.loadMore(this.infinityModel)
    }
`

And the load-more-button template looks like this:
` <button>{{loadText}}</button>`

Any ideas what I'm missing?

**Comment by snewcomer** [comment]
@MatthewPardini is `races` and instance of `InfinityModel`? e.g. the result of calling `this.infinity.model('races');`?  It decorates your "model"/data with extra properties to track pages, number of items, etc.

https://github.com/ember-infinity/ember-infinity/blob/master/addon/lib/infinity-model.js

**Comment by MatthewPardini** [comment]
@snewcomer Yes it is. I pass params and an InfiniteScrollModel extension as arguments as well, but yes, it is the result of that call.
