### ISSUE TITLE
Need to override bound parameters with query params

### ISSUE THREAD

**Issue by rizkysyazuli** [hhff/ember-infinity#227]
I just need some suggestions to solve this problem.

So i have a list of content that, if the user is logged in, will be filtered based on their children's age. This `age` param is computed and passed to infinityModel as a bound parameter.

But this list should also be filterable. there's a dropdown where you can select other age options. which will also pass an `age` param and transition the page.

Obviously, my question is how do i modify/override the `age` bound param with the query param.

Here's my infinityModel:

```javascript
articles: this.infinityModel('article', {
  perPage: 4,
  startingPage: 1,
  category_id: params.category_id,
  age: params.age,
  modelPath: 'controller.model.articles'
}, {
  age: 'userChildAge'
})
```

**Comment by snewcomer** [comment]
@rizkysyazuli thanks for the issue!  A few questions.  

1.  Is that computed re-firing when you want it to (not caching stale data)?

2.  When you say the page transitions, does that mean the `model` hook for that route is refired?

3.  Also, do you happen to be familiar with [query params](https://guides.emberjs.com/v2.14.0/routing/query-params/)?

**Comment by rizkysyazuli** [comment]
hi @snewcomer your answer:

1. nope. because i'm using ember-ajax to update the user data, while using Ember Data to store the "currrent" user data, which i got the `age` property from. So both of them is not syncing.
2. I have these settings in the route. so it should be right?
```
queryParams: {
  category_id: {
    refreshModel: true
  },
  age: {
    refreshModel: true
  },
  month: {
    refreshModel: true
  }
}
```
3. Only the basics.

**Comment by snewcomer** [comment]
@rizkysyazuli So you are modifying `age` when selecting a new `age` param from the dropdown, right?  That will cause the model hook to re-fire and send off an ajax call to get a new list of `articles`.  That would lead me to believe the bound param isn't needed (don't quote me on it though b/c maybe I'm not understanding something).

**Comment by snewcomer** [comment]
@rizkysyazuli seems like a userland bug.  If you are still having a problem would be happy to look at the app or on ember-twiddle.
