### ISSUE TITLE
Ifinitymodel not updating when transitioning back to the parent route 

### ISSUE THREAD

**Issue by DayanJonker** [hhff/ember-infinity#228]
Hey,

I have a list of forms witch are generated by a CP. I'm using ember-infinity to load the records, but when i'm in the infinite route and try to delete a record(delete route) and transition back to the overview route , the record is deleted but the list is not updated. I can see the CP is not being fired even though the dependent key is correct. So i have to refresh to update my overview, is this expected behavior?

Thnx in advace!

**Comment by snewcomer** [comment]
@DayanJonker What is the dependent key?  Also when you transition back to the list route, are you hitting the `model` hook of the route again...i.e. making another fetch for the forms?  Or does that only happen once?

**Comment by DayanJonker** [comment]
And when i'm not in the infinite route, and delete a record the CP updates the overview as expected.

**Comment by snewcomer** [comment]
@DayanJonker first one thing that might help is the computed property cache busting key [here](https://guides.emberjs.com/v2.14.0/object-model/computed-properties-and-aggregate-data/#toc_code-code-vs-code-each-code).  i.e. `model.forms.[]`

**Comment by snewcomer** [comment]
Second your computed does `model.forms`.  But it looks like you do `controller.set('forms', models.forms);`.  Thus it would be `computed('forms.[]')`.  Let me know if that changes anything.

**Comment by DayanJonker** [comment]
I ended up using a getter to fetch the forms and using 'model.forms.@each.isDeleted' as dependent key. 
``` 
  existingForms: computed('model.forms.@each.isDeleted', 'model.forms.[]', {
    get() {
      return this.get('model.forms.[]').filter(form => form.get('isDeleted') !== true);
    }
  })
```

Thanks for pointing me in the right direction! And thanks for the addon!
