### ISSUE TITLE
Support non-blocking model hook

### ISSUE THREAD

**Issue by Duder-onomy** [hhff/ember-infinity#232]
Seems like ember-infinity cannot support a non-blocking model hook, the failure is in the way the route mixin asks the 'infinityModel' that is passed to it from the infinity-loader for state. The infinityModel that the infinity-loader passes around is not promise aware.

For example, this does not work:
```javascript
export default Ember.Route.extend(InfinityRoute, {
  model() {
    return {
      posts: this.infinityModel('post', {
          modelPath: 'controller.model.posts',
          perPage: 10,
          startingPage: 1
      }),
    };
  }
});
```

I have a [fork](https://github.com/Duder-onomy/ember-infinity/tree/adds-non-blocking-model-hook-support) where I have fixed this. Basically, we just need to have promise support all-ova-the-place.

**Comment by snewcomer** [comment]
@Duder-onomy Hey thanks for putting in the issue!  Just going to paste this in here before reviewing your PR and thinking through some things.  We started a 1-0 branch.  Just need to put some finishing touches and improve the docs before releasing.  Essentially this puts a better path for [multiple](https://github.com/hhff/ember-infinity/issues/202) infinity models and an extensible infinityModel.  Moreover, we do support custom service (non-Ember Data) requests as well.  

Try it out if you want!

https://github.com/hhff/ember-infinity/tree/1-0

**Comment by Duder-onomy** [comment]
Sounds great! I will try the `1-0` branch today at work and see if our test suite passes. Looking forward to getting the non-blocking PR (or something that solves the same issue) into this project. We are using it a ton @ thedyrt.com.  Checkout our dogs page, uses Amazon image recognition service to make a page of all the dogs on our site, of course, using ember-infinity thedyrt.com/dogs

Anyhow, looking forward to the 1-0.  I also have a infinity loader that works with horizontal scrolling things you might want to lazy load, I will dust it off and see if it is worthy of a PR.

**Comment by snewcomer** [comment]
@Duder-onomy thedyrt seems pretty rad!.  Definitely support what you are trying to do here.  Let's take a look at the 1-0 branch and go from there if you don't mind.  I should have pinged you right away about moving towards a 1-0 release 😞 .

**Comment by snewcomer** [comment]
@Duder-onomy this [PR](https://github.com/hhff/ember-infinity/pull/237) implemented the non blocking hook you were looking for.  Its on the `1-0` branch.  Let us know what you think and if it works for you!

**Comment by Duder-onomy** [comment]
@snewcomer This looks great! I pulled your 1-0 branch into our app and all tests pass. Deploying it to staging right now to run the gauntlet. I will probably wait for you to relase the new version to actually pull it into production as the 1-0 branch changes a little more than just the model hook. 

A few things I noticed in the 1-0 branch. 

* I got deprecation warnings to move the `perPageParam` and `pageParam` to the infinityModel invocation but not the `totalPagesParam`. Would make sense to have deprecation warnings for all three IMO. 
* The deprecation warnings I got also had deprecations of their own: https://emberjs.com/deprecations/v2.x/#toc_ember-debug-function-options, seems like you just need to pass some options to the deprecation. 

Otherwise everything looks great! My pages were rendering super slow, but I suspect that is my problem not yours. ( i will update you shortly if it is from this lib )

The only other, unrelated to non-blocking-models thing I will say, cause I have your attention. Is that I think it would make sense to use 'ember-in-viewport' to handle the 'in-viewport' checking of the infinity loader. I took a look at my `horizontal-scroll-infinity-loader` component that I wrote and it is basically your `infinity-loader` but using ember-in-viewport. This also makes sense to offload all the scroll and offset logic onto that super well supported / tested addon. In addition, It would make your `infinity-loader` component super simple and clear. 

Anyhow, thanks to you @snewcomer and @hhff 
I will leave it up to you if you want to close this.

**Comment by snewcomer** [comment]
@Duder-onomy Everything you said seems legit.  Really appreciate the thought in the above comment!  :fist_oncoming: 

I think `ember-in-viewport` is a great addition we can add to this.  Looking to get 1-0 in by the end of the year so let's see where this falls in priorities.  I'll create an issue and we can figure out when to tackle.

The deprecation warnings I'll try to fix in an existing PR tonight or tomorrow.
