### ISSUE TITLE
1-0 branch, Infinity-loader's `destroyOnInfinity` does not seem to work

### ISSUE THREAD

**Issue by Duder-onomy** [hhff/ember-infinity#243]
Hi! 
I am not positive, but the `destroyOnInfinity` property available on the `infinity-loader` no longer seems to work. 

I can confirm that [this line](https://github.com/hhff/ember-infinity/blob/1-0/addon/components/infinity-loader.js#L146) is called. But the element stays in the DOM... nothing happens.  If you add the `destroyOnInfinity` to the dummy app, the element never goes away.  I can write a failing test for it if you need. 

Since everyone is pushing on a 1-0 release, it might make sense to instead toggle the `isVisisble` attribute on the component? I am not sure that components are supposed to be destroying themselves...

Easy workaround, Add this to your CSS:
```css
.infinity-loader.reached-infinity {
  display: none !important;
}
```

**Comment by snewcomer** [comment]
@Duder-onomy  Welp you are right.  Even tried with some scheduling timers and still doesn't destroy.  I'll try to dig in and see what we are doing wrong!

**Comment by snewcomer** [comment]
Put together this twiddle and `destroy` doesn't seem to do what I thought.

https://ember-twiddle.com/2c6625b2133a596af791fc817f88cb8c?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs

We can look into the Ember side, but if nothing materializes, then I wonder if we should remove that computed and add a property (`isFinished` or `isLoaded`) to the `InfinityModel` (see 1-0 branch) and then we can update the README showing an `if` or `unless` block around the loading-component.

**Comment by snewcomer** [comment]
@Duder-onomy What do you think about the above?

**Comment by Duder-onomy** [comment]
@snewcomer Yeah, haha, glad I am not crazy. 

I honestly feel like it should just hide itself.
Change the property name to `hideOnInfinity` then toggle the `isVisible` property. I think that is super simple and a very easy find-replace path to upgrading. 

If you moved the logic upstream, via the readme wrapping it in a `if` block, I feel like... it would be nice.... but more complex.

Just my opinion though. Open to whatever you come up with.

**Comment by snewcomer** [comment]
@Duder-onomy ah that might be even better!  Awesome idea :+1:   Could add to #242 but still waiting for an upstream PR into ember-in-viewport :( .  It might be sitting there for a while, so maybe you/I could do a PR into the 1-0 branch instead.

**Comment by Duder-onomy** [comment]
Totally. I will PR into the 1-0 branch and add some notes to the readme for upgrading.
