### ISSUE TITLE
upgrade from 0.0.4 to 0.0.8 causes Cannot find module 'ember-cli-version-checker'

### ISSUE THREAD

**Issue by ashrafhasson** [hhff/ember-infinity#27]
Hi there,

Thanks for the awesome addon.
I've just upgraded from 0.0.4 to 0.0.8 and now it shows the error:
```javascript
Cannot find module 'ember-cli-version-checker'
```
when starting with `ember s`. While I can certainly include it in my package.json, I wonder whether this was meant to be included as a dependency for the app to include?

**Comment by cgwic** [comment]
its about (discoursinng)
[https://github.com/hhff/ember-infinity/pull/26]
or u can use (my fork)[https://github.com/cgwic/ember-infinity] with all compatible to ember-infinity
im using it with my [https://github.com/cgwic/stream-fan] on openshift [http://streamfan-cgwic.rhcloud.com]

**Comment by hhff** [comment]
Looks like it belongs in dependencies, not devDependencies

**Comment by hhff** [comment]
@cgwic just merged your PR; sorry it was hanging!!  Will cut 0.0.9 shortly

**Comment by hhff** [comment]
just tried this with 0.0.9 in a fresh CLI app, and all is good
