### ISSUE TITLE
documentation of infinityModelUpdated and infinityModelLoaded

### ISSUE THREAD

**Issue by ashrafhasson** [hhff/ember-infinity#28]
Hi there,

I wonder if infinityModelUpdated and infinityModelLoaded are meant to only be internal? I'm using them for notification and verification, just wondering if they've been missed in the documentation?

Thanks,

**Comment by hhff** [comment]
Hi @ashrafhasson !  They just simply aren't documented; the lib doesn't use them internally, they're there for developers to use.

I'd love a PR documenting them!

**Comment by ashrafhasson** [comment]
@hhff I've happily documented it in commit aeefa12 and sent you a PR.
Thanks,

**Comment by hhff** [comment]
Thanks!!  Will review in the coming week x
