### ISSUE TITLE
Possibility to reset infinityloader via controller

### ISSUE THREAD

**Issue by temo44** [hhff/ember-infinity#31]
I can't seem to find the option.

When I select new filters, I want to 'reset' infinity as it were. However, I don't know if it's possible as of this moment with ember-infinity?

Thanks!

**Comment by hhff** [comment]
@temo44 - do you mean clear the `infinityModel` ?  If that's the case, you can just do that in the controller!

**Comment by temo44** [comment]
Yeah that's one part I would like to know how? Is it just `this.set('infinityModel', null)` ?

Also, in my application I do the infinity call in the model of the route (`return this.infinityModel("product", { perPage: 12, startingPage: 1 });
`). However, I would also like to call this method in an action of the controller. Is that possible?

**Comment by hhff** [comment]
Actually, I'd probably do it all from the route.

Send an action from somewhere on your template up to the `infinityRoute` called something like "changeFilter", ie:

```js

actions: {
  changeFilter(filterName) {
    // Clear the current model
    this.infinityModel("product", { perPage: 12, startingPage: 1, filter: filterName })
    .then((infinityModel) => {
      this.set(this.get('_modelPath'), infinityModel);
    }).catch(() => {
      console.log("Error");
    });
  }
}
```

**Comment by temo44** [comment]
Hm I always thought that user interaction was always handled from the controller, not the route (route being only for initial stuff). I'll try adding a action on the route side :).

**Comment by hhff** [comment]
Ember 2.0 is not even going to deprecate controllers!  It's good practice to start moving away from them where possible!

**Comment by temo44** [comment]
Woot I didn't know that! Thanks for the tip:)!
