### ISSUE TITLE
Update for Ember 2.0

### ISSUE THREAD

**Issue by hhff** [hhff/ember-infinity#32]

**Comment by temo44** [comment]
Any news on this? When updating to Ember 1.13, I get a deprecated warning on the this.store.find method in the mixin.

It should now be .query() :p

**Comment by hhff** [comment]
word!  haven't had a chance to look into it as of yet.

**Comment by hhff** [comment]
@temo44 - letting you know that I should have something soon.  See: https://github.com/ember-cli/ember-cli/issues/4339

**Comment by varoot** [comment]
I'm patiently waiting for this. Let me know if you need help testing it.

**Comment by hhff** [comment]
Thanks @varoot - i just need a chance to write a test for #48 and I thinkkkk we're good

**Comment by dj-hedgehog** [comment]
@hhff:
Now that Ember 2.0 is officially out will you merge the commit?

**Comment by hhff** [comment]
@dj-hedgehog ill merge it when I get a chance to finish it.  juggling 4 clients at the moment, violins, sad music etc etc

**Comment by mike-north** [comment]
I'll soon need to handle this if it's not addressed soon. @hhff can you brain dump any "ember-infinity for  ember 2.0" thoughts/plans on this ticket

**Comment by mkorfmann** [comment]
Hey @hhff, Hey @mike-north,

I will look into updating ember-infinity to 2.0 this week. Or are you, @mike-north, already working on a PR with updates for 2.0?

**Comment by mike-north** [comment]
I have no code written for this yet, but am eager to get this addon working with the current ember release

**Comment by hhff** [comment]
@mike-north sorry just saw your note above!

I think the first iteration re: 2.0 stuff should be to get everything working as minimal as possible.  Getting my ED 1.13.x branch in will help.

Been looking at https://github.com/mixonic/ember-cli-deprecation-workflow as a possible way to handle the transition between Ember Data versions.

The next big feature for this lib will be allowing it to work sans-Ember Data.  It's not totally unrelated to the update to 2.0, as we'll need the concept of a "promise generator" for the infinityRoute.

Also, once we're 2.0 compatible, I'm keen to cut the first release on 0.1.x track!

**Comment by mike-north** [comment]
Perhaps a good temporary solution to un-block people is to have an `ember-data-2` branch that people can point to. This would mean that the code can be different (i.e., the new `store` API) from what's needed for ember-data 1.x, with no need to figure out how to support both at the same time.

When the tight coupling to ember-data is removed, this will become a non-issue. Perhaps we never will even need to solve the hard problem (maintaining support for ED 1.x and 2.x at the same time)

**Comment by hhff** [comment]
jah, #48 just needs a test, and should be fine. 

u know what, I'll do it first thing tomorrow
