### ISSUE TITLE
Babel ES6 Polyfill required?

### ISSUE THREAD

**Issue by hhff** [hhff/ember-infinity#33]

**Comment by truenorth** [comment]
FWIW, babel will soon inject polyfills "automagically" as needed. The goal is to make it transparent to developers, so you don't have to worry about the "Babel runtime" dependencies at all

**Comment by hhff** [comment]
Thanks @truenorth - yeah I saw those threads.  Noticed the demo wasn't working on iOS devices.  For now I reckon we inject the polyfill into the dummy/demo app, and add a gotcha to the `README`.

Given you're the Github Pages master, If u do the dummy app polyfill I'll update the readme?

**Comment by truenorth** [comment]
@hhff sounds good :)

**Comment by hhff** [comment]
u da man @truenorth
