### ISSUE TITLE
_bindScroll in infinity-loader.js sets wrong scroll element

### ISSUE THREAD

**Issue by temo44** [hhff/ember-infinity#5]
There is actually one issue and one suggestion :)

1) when the page renders the infinity-loader component it assigns the guid to the ID. This makes the scrolling never trigger:

the html to support the ID assigning (how it's rendered):
```html
<div id="ember479" class="ember-view infinity-loader">  <span>Loading Infinite Model...</span>
</div>
```

infinity-loader.js

```javascript
Ember.$(window).on("scroll."+this.get('guid'), function() {
```

should be
```javascript
//mind the space
Ember.$(window).on("scroll #"+this.get('guid'), function() { 
```

2) I would like to suggest making a string property 'scrollElement' that is used to determine what scroll element is used, with a default to window. My application has the overflow on a different element than window.

```javascript
Ember.$(window).on("scroll."+this.get('guid'), function() {
```
will be

```javascript
Ember.$(scrollElement).on("scroll."+this.get('guid'), function() {
```

**Comment by hhff** [comment]
Hi @temo44 !

Thanks for this!  Check this [link](http://api.jquery.com/on/#event-names).  It explains why we're using the `infinity-loader`'s guid for the event namespace.  It's standard jQuery practise to use `.` to namespace an event.  Seeing as a developer will probably be binding other scroll events to the window, we want to be sure to only remove this particular one when the `infinity-scroller` is destroyed.  Make sense?

Also - check out the latest release (just released this morning) #4 - it now has a "scrollable" attribute that can be used to pass in a selector string :smile:

**Comment by temo44** [comment]
Thank you for the reply @hhff ! 

It makes total sense. However, won't the selector still be incorrect, as Ember generates infinity-loader's guid as an ID, and not a class?

Cool that the feature is introduced :smile:.

Awesome addon btw!

**Comment by hhff** [comment]
Thanks @temo44 !  

The guid is only used as the event namespace - ie: the unique string that "scrollable" (usually the window) uses to identify the event name.  It's not a selector - it's a scroll event with a unique namespace.

it could be 
```js
Ember.$(scrollElement).on("scroll."+Math.random(), function() {
```

But a GUID is guaranteed to be unique.  make sense?

**Comment by temo44** [comment]
Aaah thanks! It totally makes sense now. 

I know where my thought process goes wrong :smile: ! I still thought it was part of the problem(hence, the idea that it's a selector instead of a namespace. Thank you so much!
