### ISSUE TITLE
Overwrite infinity-loader template no longer works

### ISSUE THREAD

**Issue by himynameisjonas** [hhff/ember-infinity#51]
Hi. I just updated my ember app (ember from 1.12.2 to 1.13.2 and ember.infinity from 0.0.4 to 0.0.10) and since then my `app/templates/components/infinity-loader` is no longer used, instead I'm seeing the default template. Don't know where to start looking into this.

**Comment by hhff** [comment]
Jah, this is a change in ember itself.  It confused me for a while with a different project I just upgraded to 1.13.2 - not sure if this is a regression or a fix.

The work around for now is to copy the component file to your host application, and import the layout from its location in your host app, then pass that as to the layout attribute on your local component file.

**Comment by aaronrenner** [comment]
@hhff. Could you provide more detailed instructions for this workaround? I'm not quite sure what you mean.

**Comment by hhff** [comment]
Run `ember g infinity-template`, then create a new file in your host application at `app/components/infinity-loader.js` like so:

```js
import layout from '../templates/components/infinity-loader';
import infinityLoader from 'ember-infinity/components/infinity-loader';

export default infinityLoader.extend({
  layout: layout
});
```

Gonna investigate this now!

**Comment by aaronrenner** [comment]
Thanks, @hhff.

**Comment by hhff** [comment]
Lets keep this open until I fix this without the above workaround

**Comment by trabus** [comment]
The basic problem is that when the layout is defined, you have to specifically override the layout. Once the layout definition is gone from the addon template, it will lookup the template in the app, and when the user has a template in their app with the same name, that template will win over the addon's template in the app folder.

**Comment by hhff** [comment]
so ur saying I have to delete 2 lines of code @trabus 

i think i can handle that

**Comment by hhff** [comment]
oh and move 1 file

still, i can handle it

**Comment by trabus** [comment]
Or add one file to your blueprint. ;)

**Comment by hhff** [comment]
thanks @trabus !  just want to maintain the old override process for people updating to new versions.  I've also stacked the component with so much good stuff like class name binding that I only want super users to have the component file in their host app.
