### ISSUE TITLE
Infinity conflicts with liquid-fire

### ISSUE THREAD

**Issue by temo44** [hhff/ember-infinity#52]
So we've started using the liquid fire addon and whenever I try to animate a page that contains ember-infinity, I get the error that there are multiple scrollable elements are found.

After some short digging, it appears that liquid fire clones the whole render field and then animates that part.

I'm using liquid-if. I'll let you know when I have a working work-around

**Comment by temo44** [comment]
Well I fixed this issue with putting something extra in the selector:

    scrollable="div.liquid-container div.velocity-animating div.scrollable"

I added `div.liquid-container div.velocity-animating`. DidInsertElement is triggered twice. Both times there's only one `velocity-animating` class present, which is nice.

The only issue that remains is that liquid fire destroys the scrollbar itself. It's not possible for me to scroll xD. Perhaps that's one other issue on its own.

**Comment by hhff** [comment]
Thanks @temo44 !  Liquid Fire does some wild stuff that I don't quite understand. @ef4 might be able to shed some light!

**Comment by ef4** [comment]
@temo44 is right about liquid-fire rendering multiple copies of your template. That is how we are able to animate between the old and new states with both states on screen at the same time.

It may take some tweaking of CSS properties, but I think you should be able to get this all working together.

**Comment by temo44** [comment]
@ef4  @hhff  Thanks guys. I fixed it.

I wanted the 'fade-in' animation to whatever page is being rendered after the login page. However, I wanted that fade-in over the whole page, not just the route(outlet) that was being rendered, *after* everything has been rendered.

So I took the custom animation example from the liquid fire tutorial page (http://ef4.github.io/liquid-fire/#/transitions/primitives). The only 'tweak'  I thought that was necessary was that I put `Ember.run.scheduleOnce('afterRender'....` around the animation of the new element.

So after this I started testing and the thing I mentioned about a cloned element occurred. Today, however, I noticed that the element won't be cloned when you do *not* animate the old element. And luckily for me, I don't even want to animate the old element :). So everything is fixed, without the use of css tweaks.

**Comment by hhff** [comment]
:+1:

**Comment by kellyselden** [comment]
@temo44 you might want to add a little "working with liquid-fire" section to the readme. I'm sure others will run into this at some point.

**Comment by hhff** [comment]
good point @kellyselden - just gave you push to this repo, btw

@temo44 - please hit us a with a lil PR for the readme!!

**Comment by temo44** [comment]
Haha bear with me @kellyselden @hhff, I've a) never contributed to a project before and b) am in the middle of a relocation, so I've a little spare free time. 

I'll try write up something in the weekends. Thanks! :)

**Comment by hhff** [comment]
no worries :heart:

**Comment by hhff** [comment]
@temo44 - wanted to see if you were still down to write a little section in the Readme explaining the problem and how you got around it?  Supporting Liquid Fire is super important for us :)

**Comment by temo44** [comment]
@hhff I will try to write my little piece tomorrow or the day after! We created a custom infinite scrolling solution so we're going to drop ember infinity in one of the upcoming releases I'm afraid.

I will try to check up on Infinity in my free time though!

**Comment by hhff** [comment]
all good @temo44 !  would love to properly understand your liquid fire fix regardless.  Even if you post it here I can actually update the README

**Comment by temo44** [comment]
Well, first of all I wanna apologize for the very late response. I've been really busy. Second of all, I have some bad news. 

The last change that I did to our project was to just remove liquid-fire altogether. The reason for this is that in our use-case you could easily replace liquid-fire for pure css animation.

As you can read in my very first post, we used a liquid-if statement to make a transition over the entire page. However, we solved the whole duplicate element story by creating a normal if that adds a css class to the container that contains an animation. This makes the page look like it is fading in. 

Now I know this won't solve the problem with normal liquid-fire transition and I'm sorry I can't be of any use in case. However, if we ever stumble across a problem like that. I will create another issue or PM @hhff. All I can say is that css animation can bring you a long way (also in terms of performance btw)

**Comment by hhff** [comment]
ok - thanks @temo44 !
