### ISSUE TITLE
Update current model is not working

### ISSUE THREAD

**Issue by mshafivk** [hhff/ember-infinity#53]
How can I update currentModel from a route action ? now it not seems to be working?

Thanks

**Comment by hhff** [comment]
Hi @mshafivk - we don't currently support 1.13.x - but I'll get to it eventually.

**Comment by mshafivk** [comment]
Thanks, I got it working locally using mockdata. But when I deployed it, I got an error saying, "could not fetch infinityModel. Please check your serverside configuration". I can see response json coming in from service. It is same as I expected. You have any Idea why it is happening

**Comment by hhff** [comment]
@mshafivk - I think it's probably got to do with the ember data version you're using.  Can you dump all of that here?

**Comment by hhff** [comment]
closing this for now - please reopen if you're still having trouble @mshafivk
