### ISSUE TITLE
Unable to send along extra options

### ISSUE THREAD

**Issue by temo44** [hhff/ember-infinity#6]
For my application I would like to send along extra options, like sorting / active / etc. filters. Now I implemented some extra logic for me in the route.js, but I guess creating an issue would be the right thing to do :).

**Comment by joshudev** [comment]
I had this issue today too. So I've forked and created a pull request. I handled this by adding a 'params' option which gets merged into the store.find request. 

Pull request: https://github.com/hhff/ember-infinity/pull/7
Fork: https://github.com/joshudev/ember-infinity.git

**Comment by temo44** [comment]
@joshudev Nice solution. However, wouldn't it be better to not use a params object and just extend the object itself?

**Comment by joshudev** [comment]
I did think about doing it that way, but then wondered whether it's cleaner to use a params object in case in future there will be options that need to be set that you wouldn't want getting passed on to store.find. I don't mind so much either way, but it's more explicit with the params object.

**Comment by temo44** [comment]
Haha I agree  on that as well :smile: . Both has it's pros and cons. Let's see what @hhff has to say about it

**Comment by joshudev** [comment]
Yeah I'm just happy I got me an infinite scroll! It's funny that I went to log the same issue only 30 mins after you did!

**Comment by hhff** [comment]
Hey duders!

Thanks so much for the PR!  This is definitely something we need.  Ultimately, all of the params will be passed into the `store.find` call anyway, so IMO there's no need to separate them then re-merge them.

I think we just need to jimmy-jangle the code so that it passes through the full object to the `store#find` method, but just pulls out the startingPage and perPage and sets them correctly in the final params.

Thoughts?

**Comment by joshudev** [comment]
That sounds good to me! Also I noticed the travis build is failing on my fork - I think I should have used Ember.$.extend instead of $.extend.. anyways.. so will you add this feature quite soon? I'm using my fork on the project I'm working on for the moment.

**Comment by joshudev** [comment]
p.s If you want me to adjust the fork and test, I am happy to do so.

**Comment by hhff** [comment]
I'd love if you updated your PR @joshudev !  A test or two would be nice also.

Doesn't look like we'll need $.extend with this approach at all

**Comment by temo44** [comment]
Nice, this all sounds like music to my ears, haha. Thanks you guys!

**Comment by bruce** [comment]
Came to post the same issue. Glad to see it's already underway! :+1: :smile:

**Comment by bruce** [comment]
Since it's been a few days, I've submitted a PR (#9) with passing tests along these same lines, including acceptance and unit tests. Comments welcome.

**Comment by joshudev** [comment]
Thanks @bruce. Looks good! @hhff - it would be great to have that merged in as soon as possible.

**Comment by hhff** [comment]
Woo! 

reviewing this now

**Comment by hhff** [comment]
closed via #9
