### ISSUE TITLE
Should we do versioning lockstep?

### ISSUE THREAD

**Issue by hhff** [hhff/ember-infinity#64]
Summoning @kellyselden @mike-north

Wondering if it makes more sense to lock the version here to Ember CLI?  That way we just guarantee that it supports the corresponding Ember CLI version (and it's bundled Ember & Ember Data versions)...

I see pros & cons to it.

Thoughts team?  @stefanpenner / @rwjblue do you think minor addons should adopt the lock-step versioning approach also?

**Comment by rwjblue** [comment]
I personally think that addons should use useful version numbers for their consumers (aka not lockstep).

**Comment by mike-north** [comment]
agree with @rwjblue. Ideally there isn't tight coupling between addons and framework minor/patch versions. Ember-data is an exception

**Comment by hhff** [comment]
word!
