### ISSUE TITLE
Add code coverage % changed to pull requests

### ISSUE THREAD

**Issue by kellyselden** [hhff/ember-infinity#65]
It's pretty easy to do. I've added it to [ember-cli](https://github.com/ember-cli/ember-cli) and [broccoli-jscs](https://github.com/kellyselden/broccoli-jscs). Just want to see @hhff if you want it. It may require me becoming a project owner, but I don't remember. I can first try it at my current rights level.

**Comment by kellyselden** [comment]
Oh yeah, I forgot the use case. So we don't have to say please add tests to every PR, we can point at the decrease of code coverage and say please alleviate that.

**Comment by hhff** [comment]
yes def!
