### ISSUE TITLE
Reverse order functionality (asc / desc)

### ISSUE THREAD

**Issue by rafaltrojanowski** [hhff/ember-infinity#66]
Hi,
I'm not sure there is a clean way to reverse order using route action, or controller property.
I was wondering if queryParams can be used for this purpose but don't have idea how reload/update model. It makes transition but don't trigger model hook in route.

Should I implement separate route for each order?

I will be grateful for some advices how to refire model hook when some queryParam property change.

**Comment by kellyselden** [comment]
[Here](http://guides.emberjs.com/v1.13.0/routing/query-params/#toc_opting-into-a-full-transition) is the code to refresh model hook on query params change.

I'm a little confused by your exact request. Does this answer your question #55?

**Comment by rafaltrojanowski** [comment]
Thanks! This is what I was looking for.
