### ISSUE TITLE
Better Documentation for the UpdateInfinityModel hook

### ISSUE THREAD

**Issue by hhff** [hhff/ember-infinity#74]

**Comment by daniel-de-wit** [comment]
My demo application works great when loading the data on scrolling. But when trying to push objects manually into the infinity model using updateInfinityModel, like explained in the readme, it throws typeError.

For example:
```
var updatedInfinityModel = this.updateInfinityModel([
        { id: 1, name: "Hugh Francis" }
      ]);
```

Throws:
```
Uncaught TypeError: Must pass Ember.Enumerable to Ember.MutableArray#pushObjects
```

Unfortunately i'm not that familiar with Ember yet. Could you please explain how to use this?

My current setup:
```
Ember: 1.13.7
Ember Date: 1.13.8
jQuery: 1.11.3
```

**Comment by hhff** [comment]
Will look into it as part of this issue @daniel-de-wit .  My guess is you need to do something like this:
```
var updatedInfinityModel = this.updateInfinityModel(Ember.A([
  { id: 1, name: "Hugh Francis" }
]));
```
