### ISSUE TITLE
Scroll to current active element in list view

### ISSUE THREAD

**Issue by mkorfmann** [hhff/ember-infinity#84]
Hey @hhff,

Maybe there's already an easy way to do this and I'm not seeing it. Can you tell me if and how you've accomplished such behaviour before?

Cheeerio

**Comment by hhff** [comment]
what do you mean by "current active element" ?  Ember infinity doesn't do any autoscrolling

**Comment by mkorfmann** [comment]
Sure, but when I link to a specific object which is further down the scroll area in an embedded view, it's not displayed in the list view.

Maybe that's an issue out of the scope of ember-infinity, but I'd almost bet I'm not the only one having had problems with that. 

What do you think?

**Comment by hhff** [comment]
Ahh so you're using Ember Infinity with Ember List View?  I haven't tried that as of yet...

**Comment by mkorfmann** [comment]
No, just a normal bootstrap list-group with embedded routes.


like this:

| ember-infinity list | current active element from ember-infinity list |


Now, when I link or transition to an element from the list view not being
loaded within the first page, it's not in visible in the ember-infinity
list.

2015-08-31 14:06 GMT+02:00 Hugh Francis <notifications@github.com>:

**Comment by hhff** [comment]
Ahh yeah i mean if it's not in the model array (and thus not in the dom) that won't work.

You'll need to ensure it's loaded and in the dom before you can scroll to it.  If there's some way of knowing what page of results it's in, you could just call `infinityLoad` until it's ready?  Let me know if I'm not understanding correctly!

**Comment by mkorfmann** [comment]
Yes, you're understanding correctly :). My idea was implementing a fix for
this issue in ember-infinity, but maybe it's a too specific use case.

2015-08-31 14:17 GMT+02:00 Hugh Francis <notifications@github.com>:

**Comment by hhff** [comment]
kk gotcha!  Yeah i'd say its a little too specific - I'm trying to keep ember infinity as a flexible low-level tool, rather than providing too much abstraction :+1: 

you're the man @mkorfmann !
