### ISSUE TITLE
semver is not defined error when upgraded to ember 2.0

### ISSUE THREAD

**Issue by mshafivk** [hhff/ember-infinity#85]
Hi,
We are using latest version of ember-infinity. When we upgraded to ember2.0 we got the error that semver is not defined. Are we supporting latest version of ember data?

**Comment by hhff** [comment]
Yeah we support all stable versions of ember & ember data from 1.10.  This is an issue with ember-version-is.

How did you install ember infinity?  npm install or ember install?

**Comment by mshafivk** [comment]
Npm install                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Hugh FrancisSent: Friday 4 September 2015 15:25To: hhff/ember-infinityReply To: hhff/ember-infinityCc: Muhammed ShafiSubject: Re: [ember-infinity] semver is not defined error when upgraded to ember 2.0 (#85)Yeah we support all stable versions of ember & ember data from 1.10.  This is an issue with ember-version-is.

How did you install ember infinity?  npm install or ember install?

—Reply to this email directly or view it on GitHub.

**Comment by hhff** [comment]
Kk! U gotta do ember install

**Comment by mshafivk** [comment]
Thanks, It worked!

On Fri, Sep 4, 2015 at 4:10 PM, Hugh Francis <notifications@github.com>
wrote:

> Kk! U gotta do ember install
> On Fri, 4 Sep 2015 at 9:31 am Muhammed Shafi <notifications@github.com>
> wrote:
>
> > Npm install Sent from my BlackBerry 10 smartphone. From: Hugh
> FrancisSent:
> > Friday 4 September 2015 15:25To: hhff/ember-infinityReply To:
> > hhff/ember-infinityCc: Muhammed ShafiSubject: Re: [ember-infinity] semver
> > is not defined error when upgraded to ember 2.0 (#85)Yeah we support all
> > stable versions of ember & ember data from 1.10. This is an issue with
> > ember-version-is.
> >
> > How did you install ember infinity? npm install or ember install?
> >
> > —Reply to this email directly or view it on GitHub.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/hhff/ember-infinity/issues/85#issuecomment-137665400
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hhff/ember-infinity/issues/85#issuecomment-137675056>.
>



-- 

Muhammed Shafi.VK
91-9495411568

**Comment by hhff** [comment]
i'll add a note in the readme
