### ISSUE TITLE
Cursor-based pagination loads duplicate results

### ISSUE THREAD

**Issue by davidgoli** [hhff/ember-infinity#90]
Repro:

- Implement twitter-style min_id pagination, instead of page-number-based pagination, using boundParams to recalculate the query params for each page: http://www.sitepoint.com/paginating-real-time-data-cursor-based-pagination/
- Create an infinite model on a route with a template on a long page, but a small per-page count, so that the loader component is still visible after the first page of results has loaded

Result: The first page of results is rendered twice.

Although the page number is incremented, the updateInfinityModel method is not called on the first page load, and the infinityModelUpdated hook is only called afterRender and thus after the second page load is already triggered. Therefore, any params necessary for the query besides the page number have not been updated since the first page was loaded.

**Comment by UnifiedInc** [comment]
>Implement twitter-style min_id pagination, instead of page-number-based pagination, using boundParams to recalculate the query params for each page: http://www.sitepoint.com/paginating-real-time-data-cursor-based-pagination/

how did you do this? i cant find anything in the docs for ember-infinity.

**Comment by davidgoli** [comment]
@UnifiedInc This is still an open issue pending merge of #77 , at which time we'll add documentation illustrating its use. Fear not - the solution is very close at hand.

**Comment by hhff** [comment]
closed with #105
