### ISSUE TITLE
Update queryParams with page and perPage

### ISSUE THREAD

**Issue by Dragsbaek** [hhff/ember-infinity#95]
In my app, i have an infinity-list of items and a detail-view. I would like to store the current_page, so that navigating back from the detailview will take the user to the last position. 

Is that possible?

**Comment by hhff** [comment]
We don't currently have first class support for that that - it's a little tricky.

We do track the `currentPage` on the route though:
https://github.com/hhff/ember-infinity/blob/master/addon/mixins/route.js#L31

However, the lifecycle hooks are probably what you want:
```
export default Route.extend(InfinityRoute, {
  model() {
    return this.infinityModel('post');
  },
  /* Hook for when the model was updated */
  infinityModelUpdated(lastPageLoaded, totalPages, newObjects) {
    this.set('controller.infintyModelCurrentPage', lastPageLoaded);
  },
  infinityModelLoaded(totalPages) {
    this.set('controller.infintyModelCurrentPage', totalPages);
  }
});
```

Now your controller (singleton) will always know the last page that the infinityModel loaded.

Now when your route is activated, you can re-initialize your infinity model, and trigger the `infinityLoad` action until your `Route#currentPage` === `Controller#infinityModelCurrentPage`

Let me know if this works out for you @Dragsbaek !

**Comment by michaeldeitcher** [comment]
I have the same problem and have tried your solution.

I'm not sure how to keep triggering infinityLoad to bring it to the current page. I tried using scheduling afterrender but that didn't work. Please help.

**Comment by hhff** [comment]
This @michaeldeitcher !

You'd prob want to do something like this:

```
export default Route.extend(InfinityRoute, {
  model() {
    let defaultPerPage = 12;
    let infinityPageToRestore = this.get('controller.infinityModelCurrentPage');
    
    // We have a page to restore from the controller
    if (infinityPageToRestore) {
      // Trigger the initial page load as a single requset
      return this.infinityModel('post', { perPage: defaultPerPage * infinityPageToRestore }).then(() => {
        // reset the _perPage var so that future loads don't use the initial perPage length
        this.set('_perPage', defaultPerPage); 
      });
    }
    return this.infinityModel('post', { perPage: defaultPerPage });
  },

  /* Track the last current page */
  infinityModelUpdated(lastPageLoaded, totalPages, newObjects) {
    this.set('controller.infintyModelCurrentPage', lastPageLoaded);
  },
  infinityModelLoaded(totalPages) {
    this.set('controller.infintyModelCurrentPage', totalPages);
  }
});
```

**Comment by hhff** [comment]
Keeping track of the scroll position is something you'd need to do with a scroll handler in the view & controller
