### ISSUE TITLE
"Could not fetch Infinity Model" masks other errors

### ISSUE THREAD

**Issue by grantovich** [hhff/ember-infinity#96]
At a couple places in the route mixin ([here](https://github.com/hhff/ember-infinity/blob/44a43e46f805281185c1c28fee574b88fc9808cf/addon/mixins/route.js#L194) and [here](https://github.com/hhff/ember-infinity/blob/44a43e46f805281185c1c28fee574b88fc9808cf/addon/mixins/route.js#L251)), there is a promise failure handler that catches all errors and throws a generic "Could not fetch Infinity Model" error. This makes it quite difficult to determine what the actual error was – in my case the server response was successful, and I had to do some "pause on all exceptions" debugging to find out that it was ember-data telling me an association wasn't set up correctly. Is there an advantage to doing things this way? Why not allow the real error to surface?

**Comment by hhff** [comment]
thanks @grantovich - yeah that's a good point.  I think we should probably remove all error handling from server promises, and leave them only for validation type errors.

@mkorfmann @mike-north @kellyselden - thoughts / tips here?

**Comment by hhff** [comment]
just chatted with @mkorfmann - we'd like to ensure we return the error from the promise callback, but instead of throwing, we'll log an `Ember.warn`.  That way nothing will be swallowed - and the error will be clearly ember-infinity related

We're waiting for #88 to get into the codebase before doing new work on it - so we'll get to this hopefully soon - thankyou @grantovich !

**Comment by grantovich** [comment]
Thanks for the prompt response :smiley_cat: I look forward to those changes.

**Comment by davidgoli** [comment]
@grantovich FYI #88 has merged

**Comment by hhff** [comment]
@grantovich - feel like writing a PR for this? :heart:

**Comment by grantovich** [comment]
This was something I encountered on a free-time project that I work on very infrequently, so I'm not sure if I'll be able to get to it in the near future :crying_cat_face: I'll update here if I find some time to work on it.

**Comment by hhff** [comment]
kk - thanks anywhoo @grantovich !

**Comment by davidgoli** [comment]
Fixed with https://github.com/hhff/ember-infinity/pull/125
