### ISSUE TITLE
_canLoadMore doesn't fetch totalPages

### ISSUE THREAD

**Issue by szsoppa** [hhff/ember-infinity#99]
I have a problem witth totalPages parameter. I use kaminari gem together with grape to serve paginated data from server. Payload header looks like this: 
```
{
  "x-per-page": "20",
  "x-offset": "0",
  "etag": "W/\"e7fd94178cf2d6aa33c6599b64bd29f3\"",
  "vary": "Origin",
  "content-type": "application/json",
  "cache-control": "max-age=0, private, must-revalidate",
  "x-runtime": "0.057154",
  "x-total-pages": "10",
  "x-next-page": "2",
  "x-page": "1",
  "content-length": "6057",
  "x-total": "192",
  "x-request-id": "3d84c4c7-4c8e-4d78-a8c5-ae2c535b09b7"
}
```
As you can see total-pages is present here but when I stopped `_canLoadMore` in my route to see what's going on there I got nothing when trying to to this `this.get('_totalPages')` It seems like it doesn't fetch totalPages. When I return true in `_canLoadMore` everything works fine.

**Comment by kellyselden** [comment]
The response needs to look like this:
```js
{
  items: [
    {id: 1, name: 'Test'},
    {id: 2, name: 'Test 2'}
  ],
  meta: {
    total_pages: 3
  }
}
```

**Comment by szsoppa** [comment]
Thank's for reply, works great now :)

**Comment by dja** [comment]
@szsoppa did you find a good solution for including the pages data in the JSON response under meta? I'm using headers now too, and can't find much on the backend with kaminari or grape on how to structure that properly.

**Comment by szsoppa** [comment]
I used https://github.com/monterail/grape-kaminari gem to return all of the data required by ember-infinity. You can see in documentation that it's pretty simple to use.

**Comment by dja** [comment]
Thanks @szsoppa - I'm still not seeing where in grape-kaminari to tell it to include the total_pages in meta as part of the json response.. Is it conflicting with active_model_serializers perhaps?

**Comment by szsoppa** [comment]
It may have a problem with `active_model_serializers`. As you can see here https://github.com/monterail/grape-kaminari/blob/master/lib/grape/kaminari.rb#L11 it should include this header out of the box. I used `grape-entity` gem to serialize data and it worked great.

**Comment by dja** [comment]
Found this https://github.com/ruby-grape/grape-active_model_serializers#custom-metadata to modify the Rails side, or this http://codeandtechno.com/posts/metadata-via-response-headers-in-emberjs/ to modify the Ember side. For anyone who might need it..

**Comment by rmcsharry** [comment]
Be aware that the default is "total_pages" with an underscore and you might be returning dasherized attribute names.

Also, the latest ASM includes links metadata by default, more [here](https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/add_pagination_links.md) on that.

I had this issue and you can read more about it [here](https://github.com/hhff/ember-infinity/issues/179).

My controller renders like this:
```
    render json: @employees, meta: { total: (Employee.count / params[:per_page].to_f).ceil }
